### PR TITLE
crossplatformability improvements

### PR DESCRIPTION
**Pull request by goleo108**
based on my work on Warsow, most changes are easily merged with patch(1), so keep in mind:
* pure check is removed to avoid problems running unofficial binaries on not officially supported platforms
* it also merges some bug fixes and silences some warnings, so it's more than necessary to build and run
* source files are adjusted to not name binaries and modules after operating system's name and CPU's architecture, this should not be a problem to you if you are going to provide binaries for 64 bit Windows, 64 bit Linux and macOS only, however, I can revert this change and keep it locally so that I'll be able to play at OpenBSD

### CODE REVIEW

**Comment by Warfork** [comment]
Hey there it's the holiday I will review this when I have time and get back to you. Thanks!

**Comment by goleo108** [comment]
sure :)

**Comment by goleo108** [comment]
@jbeich @dressupgeekout hi, I hope you both are interested in this fork of Warsow, at OpenBSD it builds, however, it fails in runtime because it can't load Droid Sans Mono font for some reason

**Comment by goleo108** [comment]
there is some mystery about `find_package(X11 REQUIRED)`, it doesn't add `-I/usr/X11R6/include` and that makes ref_gl fail to build

**Comment by goleo108** [comment]
ok, that was really stupid of me

**Comment by dressupgeekout** [comment]
@goleo108 Awesome! I'll take a closer look later this evening.

**Pull request merged**
