### PR TITLE
WIP: Update Angelscript to latest SVN revision

### PR DESCRIPTION
**Pull request by codecat**
This updates Angelscript to the latest SVN revision. To put this in perspective: we're going from a 2014 version to a 2024 version.

Some things to note:

* ~~I have not yet tested running this (I will do this shortly) - I've only made it compile (on Linux x86_64, at least). There are likely to be a lot of script errors and some runtime behavioral changes that might have to be tweaked.~~
* Some scripts had to be changed, mostly relating to `String&` function parameters. Typically the right way to pass strings around in scripts is using `const String &in`.
* I have updated `addon_any` to the latest upstream `any` addon from Angelscript, but I have not done this with `dictionary` and `array`. It could be worth upgrading these as well (there are quite a few bugfixes and optimizations there), but due to the large amount of changes required engine-wide, I have just modified them to make them work as-is for now.
* Angelscript has introduced the `property` keyword, which (by default) is required on any `get_X` and `set_X` functions, so that you can explicitly make them properties. We can revert that to the previous behavior, but that also means that `get_length()` and `length()` are at odds with each other. So I have removed the property accessors, since it seems there are no built-in scripts that are using them. (This means you can't do `arr.length` anymore, you have to do `arr.length()`.)
* This will require quite some testing with existing scripts.

Will do some testing at runtime after I post this PR.

### CODE REVIEW

**Comment by codecat** [comment]
Seems to mostly run okay. I have only tested the main menu (without clicking on anything) and the deathmatch gamemode (without actually playing for real).

**Comment by Warfork** [comment]
@Gelmo are you okay with reviewing this? If not I'll remove you.

**Comment by codecat** [comment]
Note that this is still not ready for merging, there's still a couple problems I'm trying to fix in UI.

**Comment by codecat** [comment]
Alright I'm a lot more confident in the stability now - feel free to put this to the test!

**Pull request merged**
